name       : spek
version    : 0.8.2
release    : 5
source     :
    - https://github.com/alexkay/spek/releases/download/v0.8.2/spek-0.8.2.tar.xz : 59f69b41155ee1a4552eb9f66b602fc059de8f31e3f05889f24d362b3e6c78ae
license    : GPL-3.0-or-later
component  : multimedia.audio
summary    : Acoustic spectrum analyser
description: |
    Spek is an acoustic spectrum analyser written in C and C++.
builddeps  :
    - pkgconfig(libavformat)
    - wxwidgets-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-replace-deprecated-ffmpeg-api.patch
    %configure
build      : |
    %make
install    : |
    %make_install
